### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [generalredneck/headless-selenium#1]
Hi generalredneck

Could you add a license for this script?

BTW, it's really useful :-) thanks!

Chris

**Comment by generalredneck** [comment]
Oh yeah... sorry about the delay... I just noticed this. My email gets flooded by my work repos all day :P I'll have you something tonight

**Comment by generalredneck** [comment]
I've actually got a question into Mozilla at the moment to see if I can legally use GPL and distribute a Firefox Profile. Otherwise I will be forced to take out the profile and just give the code out as a GPL. 

Also check out the changes I just made. They may make it easier where you don't have to fork the script anymore.

**Comment by ghost** [comment]
OK cool thanks I'll take a look

**Comment by generalredneck** [comment]
I'm pretty sure I fixed this problem with commit [6d49e73](https://github.com/generalredneck/headless-selenium/commit/6d49e739e2fb0b7e84670a42c0a845603e0cdd07)
